MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.9                       # [osx and x86_64]

# clang 17 seems to have issues with this build
# fixing compiler to clang 16 for now (same as conda-forge atm)
c_compiler:
  - clang                      # [osx]
  - vs2019                     # [win and x86_64]
c_compiler_version:            # [unix]
  - 16                         # [osx]
c_stdlib:
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 10.9                       # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - clangxx                    # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
cxx_compiler_version:          # [unix]
  - 16                         # [osx]
llvm_openmp:                   # [osx]
  - 16                         # [osx]
