{% set name = "pyshtools" %}
{% set version = "4.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43aa80e954e1a222436c8643d342541880f6402b23cdde9d2cd9fdd1097d4e6f

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  # catch errors
  error_overlinking: True

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    # Don't add constraints to the following 3 to use conda-forge global settings
    - numpy
    - fftw
    - liblapack
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fftw >=3.3.8
    - liblapack >=3.8
    - scipy >=0.14.0
    - matplotlib-base >=3.3
    - astropy >=4.0
    - xarray
    - requests
    - gmt >=6.1.1
    - pygmt >=0.3
    - pooch >=1.1
    - tqdm
    - cartopy >=0.18
    - ducc0 >=0.15

test:
  requires:
    - make
    - tar
    - wget
  imports:
    - pyshtools
  commands:
    - wget https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    - tar -xvf {{ name }}-{{ version }}.tar.gz
    - cd {{ name }}-{{ version }}
    - make -C examples/python -f Makefile no-timing

about:
  home: https://github.com/SHTOOLS/SHTOOLS
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tools for working with spherical harmonics

  description: |
    SHTOOLS/pysthools is a Fortran-95/Python library that can be used to
    perform spherical harmonic transforms, multitaper spectral analyses on the
    sphere, expansions of functions into Slepian bases, and standard operations
    on global gravitational and magnetic field data.
  doc_url: https://shtools.github.io/SHTOOLS/
  dev_url: https://github.com/SHTOOLS/SHTOOLS

extra:
  recipe-maintainers:
    - megies
    - moorepants
    - markwieczorek
