{% set name = "pyshtools" %}
{% set version = "4.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc4a323e9cbc905c04ae9e2e9fedeea6d76f3315a6863ede353a4dec87b8c018

build:
  number: 2
  skip: true  # [py<39]
  error_overlinking: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}  # [not win]
    - flang_win-64               # [win]
  host:
    - python
    - pip
    - setuptools
    - meson-python >=0.14
    - setuptools_scm >=8
    - pkg-config
    - jupyter
    # Don't add constraints to the following 4 to use conda-forge global settings
    - numpy
    - fftw
    - libblas
    - liblapack
    - libpgmath  # [win]
  run:
    - python
    - {{ pin_compatible('fftw') }}
    - scipy
    - matplotlib-base
    - astropy-base
    - xarray
    - requests
    - pooch
    - ducc0
  run_constrained:
    - cartopy >=0.18
    - gmt >=6.3.0
    - pygmt >=0.7.0

test:
  requires:
    - make     # [not win]
    - m2-make  # [win]
    - cartopy
    - pygmt
  imports:
    - pyshtools
  commands:
    - make -C examples/python -f Makefile no-timing
  source_files:
    - examples/*

about:
  home: https://github.com/SHTOOLS/SHTOOLS
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tools for working with spherical harmonics

  description: |
    SHTOOLS/pysthools is a Fortran-95/Python library that can be used to
    perform spherical harmonic transforms, multitaper spectral analyses on the
    sphere, expansions of functions into Slepian bases, and standard operations
    on global gravitational and magnetic field data.
  doc_url: https://shtools.github.io/SHTOOLS/
  dev_url: https://github.com/SHTOOLS/SHTOOLS

extra:
  recipe-maintainers:
    - megies
    - moorepants
    - markwieczorek
    - jan-janssen
