{% set name = "pyshtools" %}
{% set version = "4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da1d459ca04dcaec9c9637dfe8b178b53fb510333e3d106214950560a1a0d784

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - fftw >=3
    - liblapack
  run:
    - python
    - numpy
    - scipy >=0.14.0
    - matplotlib-base
    - astropy
    - xarray
    - fftw >=3
    - requests

test:
  requires:
    - make
    - tar
    - wget
  imports:
    - pyshtools
  commands:
    - wget https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    - tar -xvf {{ name }}-{{ version }}.tar.gz
    - cd {{ name }}-{{ version }}
    - make -C examples/python -f Makefile no-timing

about:
  home: https://github.com/SHTOOLS/SHTOOLS
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tools for working with spherical harmonics

  description: |
    SHTOOLS/pysthools is a Fortran-95/Python library that can be used to
    perform spherical harmonic transforms, multitaper spectral analyses on the
    sphere, expansions of functions into Slepian bases, and standard operations
    on global gravitational and magnetic field data.
  doc_url: https://shtools.github.io/SHTOOLS/
  dev_url: https://github.com/SHTOOLS/SHTOOLS

extra:
  recipe-maintainers:
    - megies
    - moorepants
